TITLE="Beej 的 C 语言编程指南"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.9.18, Copyright © August 4, 2024"

GUIDE_ID=bgc
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg)

include $(BGBSPD_BUILD_DIR)/source.make
